/*
 * Endpoints Example
 *
 * A simple Google Cloud Endpoints API example.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.SwaggerGen.Annotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class DefaultApiController : Controller
    { 

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Returns the requests&#39; authentication information.</remarks>
        /// <response code="200">Authenication info.</response>
        [HttpGet]
        [Route("/auth/info/googleidtoken")]
        [SwaggerOperation("AuthInfoGoogleIdToken")]
        [SwaggerResponse(200, type: typeof(AuthInfoResponse))]
        public virtual IActionResult AuthInfoGoogleIdToken()
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<AuthInfoResponse>(exampleJson)
            : default(AuthInfoResponse);
            return new ObjectResult(example);
        }


        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Returns the requests&#39; authentication information.</remarks>
        /// <response code="200">Authenication info.</response>
        [HttpGet]
        [Route("/auth/info/googlejwt")]
        [SwaggerOperation("AuthInfoGoogleJwt")]
        [SwaggerResponse(200, type: typeof(AuthInfoResponse))]
        public virtual IActionResult AuthInfoGoogleJwt()
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<AuthInfoResponse>(exampleJson)
            : default(AuthInfoResponse);
            return new ObjectResult(example);
        }


        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Echo back a given message.</remarks>
        /// <param name="message">Message to echo</param>
        /// <response code="200">Echo</response>
        [HttpPost]
        [Route("/echo")]
        [SwaggerOperation("Echo")]
        [SwaggerResponse(200, type: typeof(EchoMessage))]
        public virtual IActionResult Echo([FromBody]EchoMessage message)
        { 
            return new ObjectResult(message);
        }
    }
}
